#############################################################################
# Makefile for building: luks-crypt-utils
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  luks-crypt-utils.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile luks-crypt-utils.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = luks-crypt-utils1.0.0
DISTDIR = /home/owl/qtProjects/luks-crypt-utils/.tmp/luks-crypt-utils1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lcrypto -lssl -lm -lexplain -lpopt -luuid   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/afutils.cpp \
		src/cipher.cpp \
		src/device.cpp \
		src/hashfunction.cpp \
		src/ioutils.cpp \
		src/key.cpp \
		src/logger.cpp \
		src/luks-crypt-utils.cpp \
		src/luksactions.cpp \
		src/luksdevice.cpp \
		src/lukspartitionheader.cpp \
		src/luksstorage.cpp \
		src/opensslcryptoprovider.cpp \
		src/pbkdf.cpp \
		src/random.cpp \
		src/storagekey.cpp \
		src/utils.cpp 
OBJECTS       = afutils.o \
		cipher.o \
		device.o \
		hashfunction.o \
		ioutils.o \
		key.o \
		logger.o \
		luks-crypt-utils.o \
		luksactions.o \
		luksdevice.o \
		lukspartitionheader.o \
		luksstorage.o \
		opensslcryptoprovider.o \
		pbkdf.o \
		random.o \
		storagekey.o \
		utils.o
DIST          = Makefile \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		luks-crypt-utils.pro src/afutils.h \
		src/bitops.h \
		src/cipher.h \
		src/config.h \
		src/device.h \
		src/hashfunction.h \
		src/ioutils.h \
		src/key.h \
		src/logger.h \
		src/luks-crypt-utils.h \
		src/luksactions.h \
		src/luksconstants.h \
		src/luksdevice.h \
		src/lukspartitionheader.h \
		src/luksstorage.h \
		src/opensslcryptoprovider.h \
		src/pbkdf.h \
		src/random.h \
		src/storagekey.h \
		src/utils.h src/afutils.cpp \
		src/cipher.cpp \
		src/device.cpp \
		src/hashfunction.cpp \
		src/ioutils.cpp \
		src/key.cpp \
		src/logger.cpp \
		src/luks-crypt-utils.cpp \
		src/luksactions.cpp \
		src/luksdevice.cpp \
		src/lukspartitionheader.cpp \
		src/luksstorage.cpp \
		src/opensslcryptoprovider.cpp \
		src/pbkdf.cpp \
		src/random.cpp \
		src/storagekey.cpp \
		src/utils.cpp
QMAKE_TARGET  = luks-crypt-utils
DESTDIR       = 
TARGET        = luks-crypt-utils


first: all
####### Build rules

luks-crypt-utils:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: luks-crypt-utils.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		luks-crypt-utils.pro
	$(QMAKE) -o Makefile luks-crypt-utils.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
luks-crypt-utils.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile luks-crypt-utils.pro

qmake_all: FORCE


all: Makefile luks-crypt-utils

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

afutils.o: src/afutils.cpp src/afutils.h \
		src/bitops.h \
		src/hashfunction.h \
		src/luksconstants.h \
		src/config.h \
		src/utils.h \
		src/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o afutils.o src/afutils.cpp

cipher.o: src/cipher.cpp src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/luksconstants.h \
		src/config.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cipher.o src/cipher.cpp

device.o: src/device.cpp src/device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o device.o src/device.cpp

hashfunction.o: src/hashfunction.cpp src/hashfunction.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hashfunction.o src/hashfunction.cpp

ioutils.o: src/ioutils.cpp src/ioutils.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioutils.o src/ioutils.cpp

key.o: src/key.cpp src/key.h \
		src/ioutils.h \
		src/logger.h \
		src/luksconstants.h \
		src/config.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o key.o src/key.cpp

logger.o: src/logger.cpp src/logger.h \
		src/luksconstants.h \
		src/config.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/logger.cpp

luks-crypt-utils.o: src/luks-crypt-utils.cpp src/luks-crypt-utils.h \
		src/luksactions.h \
		src/luksdevice.h \
		src/storagekey.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/luksconstants.h \
		src/config.h \
		src/luksstorage.h \
		src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/logger.h \
		src/random.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luks-crypt-utils.o src/luks-crypt-utils.cpp

luksactions.o: src/luksactions.cpp src/luksactions.h \
		src/luksdevice.h \
		src/storagekey.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/luksconstants.h \
		src/config.h \
		src/luksstorage.h \
		src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/logger.h \
		src/utils.h \
		src/afutils.h \
		src/pbkdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksactions.o src/luksactions.cpp

luksdevice.o: src/luksdevice.cpp src/luksdevice.h \
		src/storagekey.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/luksconstants.h \
		src/config.h \
		src/luksstorage.h \
		src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/pbkdf.h \
		src/logger.h \
		src/random.h \
		src/utils.h \
		src/afutils.h \
		src/opensslcryptoprovider.h \
		src/ioutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksdevice.o src/luksdevice.cpp

lukspartitionheader.o: src/lukspartitionheader.cpp src/lukspartitionheader.h \
		src/luksconstants.h \
		src/config.h \
		src/storagekey.h \
		src/key.h \
		src/utils.h \
		src/afutils.h \
		src/logger.h \
		src/hashfunction.h \
		src/random.h \
		src/opensslcryptoprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lukspartitionheader.o src/lukspartitionheader.cpp

luksstorage.o: src/luksstorage.cpp src/luksstorage.h \
		src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/luksconstants.h \
		src/config.h \
		src/key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksstorage.o src/luksstorage.cpp

opensslcryptoprovider.o: src/opensslcryptoprovider.cpp src/opensslcryptoprovider.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/luksconstants.h \
		src/config.h \
		src/storagekey.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opensslcryptoprovider.o src/opensslcryptoprovider.cpp

pbkdf.o: src/pbkdf.cpp src/pbkdf.h \
		src/logger.h \
		src/luksconstants.h \
		src/config.h \
		src/luksdevice.h \
		src/storagekey.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/luksstorage.h \
		src/cipher.h \
		src/bitops.h \
		src/hashfunction.h \
		src/utils.h \
		src/afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pbkdf.o src/pbkdf.cpp

random.o: src/random.cpp src/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o random.o src/random.cpp

storagekey.o: src/storagekey.cpp src/storagekey.h \
		src/key.h \
		src/utils.h \
		src/afutils.h \
		src/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o storagekey.o src/storagekey.cpp

utils.o: src/utils.cpp src/utils.h \
		src/afutils.h \
		src/bitops.h \
		src/luksconstants.h \
		src/config.h \
		src/opensslcryptoprovider.h \
		src/key.h \
		src/lukspartitionheader.h \
		src/storagekey.h \
		src/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/utils.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

