#############################################################################
# Makefile for building: luks-crypt-utils
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  luks-crypt-utils.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile luks-crypt-utils.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES) -g -O0
INCPATH       = -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = luks-crypt-utils1.0.0
DISTDIR = /home/owl/qtProjects/luks-crypt-utils/.tmp/luks-crypt-utils1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lcrypto -lssl -lm -lexplain -lpopt -luuid   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = afutils.cpp \
		cipher.cpp \
		device.cpp \
		hashfunction.cpp \
		ioutils.cpp \
		key.cpp \
		logger.cpp \
		luks-crypt-utils.cpp \
		luksactions.cpp \
		luksdevice.cpp \
		lukspartitionheader.cpp \
		luksstorage.cpp \
		opensslcryptoprovider.cpp \
		pbkdf.cpp \
		random.cpp \
		storagekey.cpp \
		utils.cpp 
OBJECTS       = afutils.o \
		cipher.o \
		device.o \
		hashfunction.o \
		ioutils.o \
		key.o \
		logger.o \
		luks-crypt-utils.o \
		luksactions.o \
		luksdevice.o \
		lukspartitionheader.o \
		luksstorage.o \
		opensslcryptoprovider.o \
		pbkdf.o \
		random.o \
		storagekey.o \
		utils.o
DIST          = Makefile \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		luks-crypt-utils.pro afutils.h \
		bitops.h \
		cipher.h \
		config.h \
		device.h \
		hashfunction.h \
		ioutils.h \
		key.h \
		logger.h \
		luks-crypt-utils.h \
		luksactions.h \
		luksconstants.h \
		luksdevice.h \
		lukspartitionheader.h \
		luksstorage.h \
		opensslcryptoprovider.h \
		pbkdf.h \
		random.h \
		storagekey.h \
		utils.h afutils.cpp \
		cipher.cpp \
		device.cpp \
		hashfunction.cpp \
		ioutils.cpp \
		key.cpp \
		logger.cpp \
		luks-crypt-utils.cpp \
		luksactions.cpp \
		luksdevice.cpp \
		lukspartitionheader.cpp \
		luksstorage.cpp \
		opensslcryptoprovider.cpp \
		pbkdf.cpp \
		random.cpp \
		storagekey.cpp \
		utils.cpp
QMAKE_TARGET  = luks-crypt-utils
DESTDIR       = 
TARGET        = luks-crypt-utils


first: all
####### Build rules

luks-crypt-utils:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: luks-crypt-utils.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		luks-crypt-utils.pro
	$(QMAKE) -o Makefile luks-crypt-utils.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
luks-crypt-utils.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile luks-crypt-utils.pro

qmake_all: FORCE


all: Makefile luks-crypt-utils

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

afutils.o: afutils.cpp afutils.h \
		bitops.h \
		hashfunction.h \
		luksconstants.h \
		config.h \
		utils.h \
		random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o afutils.o afutils.cpp

cipher.o: cipher.cpp cipher.h \
		bitops.h \
		hashfunction.h \
		luksconstants.h \
		config.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cipher.o cipher.cpp

device.o: device.cpp device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o device.o device.cpp

hashfunction.o: hashfunction.cpp hashfunction.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hashfunction.o hashfunction.cpp

ioutils.o: ioutils.cpp ioutils.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioutils.o ioutils.cpp

key.o: key.cpp key.h \
		ioutils.h \
		logger.h \
		luksconstants.h \
		config.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o key.o key.cpp

logger.o: logger.cpp logger.h \
		luksconstants.h \
		config.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

luks-crypt-utils.o: luks-crypt-utils.cpp luks-crypt-utils.h \
		luksactions.h \
		luksdevice.h \
		storagekey.h \
		key.h \
		lukspartitionheader.h \
		luksconstants.h \
		config.h \
		luksstorage.h \
		cipher.h \
		bitops.h \
		hashfunction.h \
		logger.h \
		random.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luks-crypt-utils.o luks-crypt-utils.cpp

luksactions.o: luksactions.cpp luksactions.h \
		luksdevice.h \
		storagekey.h \
		key.h \
		lukspartitionheader.h \
		luksconstants.h \
		config.h \
		luksstorage.h \
		cipher.h \
		bitops.h \
		hashfunction.h \
		logger.h \
		utils.h \
		afutils.h \
		pbkdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksactions.o luksactions.cpp

luksdevice.o: luksdevice.cpp luksdevice.h \
		storagekey.h \
		key.h \
		lukspartitionheader.h \
		luksconstants.h \
		config.h \
		luksstorage.h \
		cipher.h \
		bitops.h \
		hashfunction.h \
		pbkdf.h \
		logger.h \
		random.h \
		utils.h \
		afutils.h \
		opensslcryptoprovider.h \
		ioutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksdevice.o luksdevice.cpp

lukspartitionheader.o: lukspartitionheader.cpp lukspartitionheader.h \
		luksconstants.h \
		config.h \
		storagekey.h \
		key.h \
		utils.h \
		afutils.h \
		logger.h \
		hashfunction.h \
		random.h \
		opensslcryptoprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lukspartitionheader.o lukspartitionheader.cpp

luksstorage.o: luksstorage.cpp luksstorage.h \
		cipher.h \
		bitops.h \
		hashfunction.h \
		luksconstants.h \
		config.h \
		key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o luksstorage.o luksstorage.cpp

opensslcryptoprovider.o: opensslcryptoprovider.cpp opensslcryptoprovider.h \
		key.h \
		lukspartitionheader.h \
		luksconstants.h \
		config.h \
		storagekey.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opensslcryptoprovider.o opensslcryptoprovider.cpp

pbkdf.o: pbkdf.cpp pbkdf.h \
		logger.h \
		luksconstants.h \
		config.h \
		luksdevice.h \
		storagekey.h \
		key.h \
		lukspartitionheader.h \
		luksstorage.h \
		cipher.h \
		bitops.h \
		hashfunction.h \
		utils.h \
		afutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pbkdf.o pbkdf.cpp

random.o: random.cpp random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o random.o random.cpp

storagekey.o: storagekey.cpp storagekey.h \
		key.h \
		utils.h \
		afutils.h \
		random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o storagekey.o storagekey.cpp

utils.o: utils.cpp utils.h \
		afutils.h \
		bitops.h \
		luksconstants.h \
		config.h \
		opensslcryptoprovider.h \
		key.h \
		lukspartitionheader.h \
		storagekey.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

